### ISSUE TITLE
Upgrade to Eslint v8

### ISSUE THREAD

**Issue by scsinke** [preactjs/eslint-config-preact#17]
Please at support for the new ESLint version

**Comment by scsinke** [comment]
@marvinhagemeister Do you consider installing the `@next` version of `eslint-plugin-react-hooks`. Or are only `stable` releases allowed?

**Comment by scsinke** [comment]
Any update on this?

**Comment by marvinhagemeister** [comment]
Resolved by #18 . Version `>= 1.3.0` includes support for ESLint v8

**Comment by marvinhagemeister** [comment]
@rburgst If you feel like this is something that should be addressed it's better to open a new issue, rather than commenting on a closed since 2021.
