### ISSUE TITLE
Parsing error with updated eslint caused by @babel/plugin-syntax-decorators

### ISSUE THREAD

**Issue by jnpwebdeveloper** [preactjs/eslint-config-preact#21]
https://github.com/preactjs/eslint-config-preact/blob/b38e3f37fc6b3f2ae45a64995bcff0a3ba3a3869/index.js#L19

After updating eslint to `8.9.0` I received the following error:

`Parsing error: Cannot use the decorators and decorators-legacy plugin together`

Removing the plugin `@babel/plugin-syntax-class-properties` helped resolve this for me:

```
babelOptions: {
  plugins: ['@babel/plugin-syntax-class-properties', '@babel/plugin-syntax-jsx']
}
```

**Comment by geisterfurz007** [comment]
Could a new version with the fix be released? It seems the last release was in December last year and the error is still an issue for me unfortunately. Let me know if I can help with that in any way!
