### ISSUE TITLE
ESLint couldn't find the config "preact" to extend from

### ISSUE THREAD

**Issue by NicHaley** [preactjs/eslint-config-preact#3]
I have installed the latest `eslint-config-preact`, and the rules appear to work great inside my IDE. However, if I run `./node_modules/.bin/eslint . --ext .ts,.js,.tsx` I consistently get the error

```
Oops! Something went wrong! :(

ESLint: 6.8.0.

ESLint couldn't find the config "preact" to extend from. Please check that the name of the config is correct.
```

All my other eslint plugins work as expected. Additionally, it is referencing my .eslintrc of my project root in the correct path.

I am using preact 10.3.3 and eslint 6.8.0.

**Comment by marvinhagemeister** [comment]
Just tried it out locally on my machine and it works fine with `eslint@6.8.0`. Does adding ```"root": true``` help? Is eslint installed locally into the project?

It could be that you have a global eslint config file somewhere. If you add the `--debug` to the eslint path we should be able to get more information about where eslint looks for configurations.

**Comment by Sasha-Sorokin** [comment]
@marvinhagemeister can you test on Node v13.8.0? (`nvm use node`)

It would work for me on Node <v12, but for >=13 it fails. There's also this message: 
```
(node:26080) ExperimentalWarning: Conditional exports is an experimental feature. This feature could change at any time
```

The message was pointed out here: https://github.com/eslint/eslint/issues/12954#issuecomment-590093784

**Comment by NicHaley** [comment]
> Just tried it out locally on my machine and it works fine with `eslint@6.8.0`. Does adding `"root": true` help? Is eslint installed locally into the project?
> 
> It could be that you have a global eslint config file somewhere. If you add the `--debug` to the eslint path we should be able to get more information about where eslint looks for configurations.

I tried `"root": true` without any luck. 

@Sasha-Sorokin I will try that out!

**Comment by NicHaley** [comment]
It worked 🎉

**Comment by marvinhagemeister** [comment]
Tracked it down to the paths not being relative in the `exports` declarations. We assumed that they would work the same way as `main` or `module` but apparently that's not the case :see_no_evil:

**Comment by chaiiplss** [comment]
I'm also facing this type of issue. Although the config file name is different. I tried the eslint forum for solution but couldn't find any.

```
ESLint: 6.8.0.

ESLint couldn't find the config "medikoo" to extend from. Please check that the name of the config is correct.
```

Is there any solution without using different version of node?

**Comment by marvinhagemeister** [comment]
@chaiiplss I think the eslint team is the right one to ask about that. Would you mind posting that on their tracker?

FYI: This repo is about an eslint preset for Preact and it's not a place to get help with general eslint problems.

**Comment by chaiiplss** [comment]
Yeah sure, will do! Thanks for reply @marvinhagemeister 😄
