### ISSUE TITLE
Error: Error while loading rule 'jest/no-deprecated-functions': Unable to detect Jest version 

### ISSUE THREAD

**Issue by psabharwal123** [preactjs/eslint-config-preact#31]
created a new preact app using create-preact with the command - npm init preact
then ran eslint --ext js,jsx src

Oops! Something went wrong! :(

ESLint: 8.57.0

Error: Error while loading rule 'jest/no-deprecated-functions': Unable to detect Jest version - please ensure jest package is installed, or otherwise set version explicitly

either create-preact should install jest or this rule should be removed from the config

**Comment by rschristian** [comment]
Jest should be a peerDep of `eslint-plugin-jest` and therefore automatically installed, but I'm okay with removal.

**Comment by psabharwal123** [comment]
@rschristian i think removal is better as create-preact no longer prescribes jest, so if someone is using another testing framework they wont have to unnecessarily download jest and all its dependencies

**Comment by rschristian** [comment]
That's reasonable.

Care to make a PR?

**Comment by psabharwal123** [comment]
done
