### ISSUE TITLE
Style rules are not disabled

### ISSUE THREAD

**Issue by ethanwu10** [preactjs/eslint-config-preact#6]
This config is not supposed to include any stylistic or subjective rules, however there are various sytlistic rules that do not appear to be disabled (even though there's a comment suggesting they should be): [preact stylistic rules](https://github.com/preactjs/eslint-config-preact/blob/6687c4931b3df7d52cdf6fca98a20d2093eb81de/index.js#L93) and [general javascript stylistic rules](https://github.com/preactjs/eslint-config-preact/blob/6687c4931b3df7d52cdf6fca98a20d2093eb81de/index.js#L151).

**Comment by marvinhagemeister** [comment]
Good catch! Rather than commenting those lines out, we should just remove them in my opinion.

**Comment by hcatlin** [comment]
Yeah, this is biting me in the butt right now! :P

I'm even trying to run off of the PR's branch– but still getting a huge number of errors when I add this (vs none without adding it)
